### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by guilhermecgs** [saullocastro/structMan#1]
Error running : 

`pip install git+https://github.com/compmech/structmanager.git#egg=structmanager`

Output is:

![image](https://user-images.githubusercontent.com/8465337/50926666-b93eba80-143c-11e9-824e-ed7dae90ec2a.png)

**Comment by saullocastro** [comment]
Dear @guilhermecgs  I created a new release 0.4.0 that should fix this installation error. I have a Master`s thesis and conference paper in case you need further real examples. The library is not complete and work well with Nastran`s SOL 200 only. 

Please, cite this release as:

CASTRO, S. G. P. et al. StructManager. Version 0.4.0. DOI: https://doi.org/10.5281/zenodo.25366100.


With Kind Regards
Saullo

**Comment by guilhermecgs** [comment]
thanks! worked just fine!

valeu demais  :-)

**Comment by saullocastro** [comment]
@guilhermecgs não esqueça de citar como mencionado acima abs
